In [34]:
import pandas as pd

In [35]:
df = pd.read_csv("../data/processed/df_final.csv")
df

,Geografía,Año,Provincia,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos
0,Alaquàs,2021,Valencia,4,1,205,8,0,100,14,0,10,8,350
1,Alaquàs,2022,Valencia,5,0,240,14,0,99,21,0,16,7,402
2,Alaquàs,2023,Valencia,13,0,178,9,0,60,35,1,8,7,311
3,Alaquàs,2024,Valencia,9,2,188,9,0,77,22,0,12,12,331
4,Alboraia / Alboraya,2021,Valencia,3,0,391,4,0,86,32,0,16,3,535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,Villanueva de la Cañada,2024,Madrid,12,0,231,15,0,101,15,0,2,2,378
772,Villaviciosa de Odón,2021,Madrid,15,0,274,13,0,173,53,0,6,3,537
773,Villaviciosa de Odón,2022,Madrid,19,0,320,8,0,182,49,0,8,4,590
774,Villaviciosa de Odón,2023,Madrid,11,0,301,17,0,234,37,0,7,6,613
775,Villaviciosa de Odón,2024,Madrid,10,0,267,20,0,175,22,0,8,4,506

# ES IMPORTANTE NO INCLUIR 2025

In [36]:
def calculo_estadistico_delitos(df):
    df = df.copy()

    lista_delitos = ["Delitos Sexuales",
                     "Homicidios",
                     "Hurtos",
                     "Lesiones",
                     "Resto De Criminalidad Convencional",
                     "Robos Con Fuerza",
                     "Robos Con Violencia",
                     "Secuestro",
                     "Sustraccion De Vehiculos",
                     "Trafico De Drogas",
                     "Total Delitos"]
   
    df = df.groupby("Geografía")[lista_delitos].mean()

    return df.reset_index()

media_delitos = calculo_estadistico_delitos(df)
media_delitos

,Geografía,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos
0,Alaquàs,7.750000,0.750000,202.750000,10.000000,0.000000,84.000000,23.000000,0.250000,11.500000,8.500000,348.500000
1,Alboraia / Alboraya,7.750000,0.000000,519.500000,10.000000,0.000000,139.750000,36.000000,0.000000,22.500000,5.250000,740.750000
2,Alcalá de Henares,54.777778,5.888889,2499.444444,53.333333,174.000000,477.888889,195.111111,0.222222,203.333333,43.222222,3707.222222
3,Alcobendas,41.333333,1.777778,1310.333333,30.666667,73.111111,339.888889,92.555556,0.000000,183.444444,28.444444,2101.555556
4,Alcorcón,33.111111,2.555556,2326.777778,29.555556,92.777778,356.444444,203.777778,0.444444,128.444444,28.555556,3202.444444
...,...,...,...,...,...,...,...,...,...,...,...,...
111,Vilassar de Mar,7.500000,0.250000,130.250000,4.000000,0.000000,86.500000,31.250000,0.000000,12.250000,1.750000,273.750000
112,Villanueva de la Cañada,12.750000,0.250000,272.500000,9.750000,0.000000,116.500000,17.000000,0.000000,4.250000,3.750000,436.750000
113,Villaviciosa de Odón,13.750000,0.000000,290.500000,14.500000,0.000000,191.000000,40.250000,0.000000,7.250000,4.250000,561.500000
114,Xirivella,13.250000,0.750000,299.750000,14.250000,0.000000,78.000000,20.000000,0.000000,13.000000,3.750000,442.750000
115,Xàtiva,14.000000,0.750000,315.500000,17.250000,0.000000,148.250000,13.250000,0.000000,16.000000,6.000000,531.000000

In [37]:
df_madrid_p = pd.read_csv('../data/raw/Poblacion/poblacion-madrid.csv', sep=';', encoding='latin1')
df_barcelona_p = pd.read_csv('../data/raw/Poblacion/poblacion-Barcelona.csv', sep=';', encoding='latin1')
df_valencia_p = pd.read_csv('../data/raw/Poblacion/poblacion-valencia.csv', sep=';', encoding='latin1')

In [38]:
df_poblacion_total = pd.concat([df_madrid_p, df_barcelona_p, df_valencia_p])
df_poblacion_total['Municipios'] = df_poblacion_total['Municipios'].str.replace(r'^\d+\s+', '', regex=True)

df_poblacion_total

       Sexo   Municipios  Periodo Total
0     Total  Acebeda, La     2025    70
1     Total  Acebeda, La     2024    68
2     Total  Acebeda, La     2023    67
3     Total  Acebeda, La     2022    62
4     Total  Acebeda, La     2021    55
...     ...          ...      ...   ...
2665  Total        Zarra     2020   346
2666  Total        Zarra     2019   359
2667  Total        Zarra     2018   365
2668  Total        Zarra     2017   381
2669  Total        Zarra     2016   440

[7590 rows x 4 columns]

In [39]:
df_unido = df.merge(df_poblacion_total, 
                          left_on=['Geografía', 'Año'], 
                          right_on=['Municipios', 'Periodo'], 
                          how='left')
df_unido

,Geografía,Año,Provincia,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos,Sexo,Municipios,Periodo,Total
0,Alaquàs,2021,Valencia,4,1,205,8,0,100,14,0,10,8,350,Total,Alaquàs,2021.0,29.649
1,Alaquàs,2022,Valencia,5,0,240,14,0,99,21,0,16,7,402,Total,Alaquàs,2022.0,29.537
2,Alaquàs,2023,Valencia,13,0,178,9,0,60,35,1,8,7,311,Total,Alaquàs,2023.0,29.825
3,Alaquàs,2024,Valencia,9,2,188,9,0,77,22,0,12,12,331,Total,Alaquàs,2024.0,30.022
4,Alboraia / Alboraya,2021,Valencia,3,0,391,4,0,86,32,0,16,3,535,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
789,Villanueva de la Cañada,2024,Madrid,12,0,231,15,0,101,15,0,2,2,378,Total,Villanueva de la Cañada,2024.0,23.799
790,Villaviciosa de Odón,2021,Madrid,15,0,274,13,0,173,53,0,6,3,537,Total,Villaviciosa de Odón,2021.0,28.030
791,Villaviciosa de Odón,2022,Madrid,19,0,320,8,0,182,49,0,8,4,590,Total,Villaviciosa de Odón,2022.0,28.152
792,Villaviciosa de Odón,2023,Madrid,11,0,301,17,0,234,37,0,7,6,613,Total,Villaviciosa de Odón,2023.0,28.750
793,Villaviciosa de Odón,2024,Madrid,10,0,267,20,0,175,22,0,8,4,506,Total,Villaviciosa de Odón,2024.0,29.273

In [42]:
df_unido[df_unido['Municipios'].isna()]

,Geografía,Año,Provincia,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos,Sexo,Municipios,Periodo,Total
4,Alboraia / Alboraya,2021,Valencia,3,0,391,4,0,86,32,0,16,3,535,NaN,NaN,NaN,NaN
5,Alboraia / Alboraya,2022,Valencia,5,0,529,7,0,121,35,0,30,5,732,NaN,NaN,NaN,NaN
6,Alboraia / Alboraya,2023,Valencia,11,0,530,18,0,145,31,0,25,8,768,NaN,NaN,NaN,NaN
7,Alboraia / Alboraya,2024,Valencia,12,0,628,11,0,207,46,0,19,5,928,NaN,NaN,NaN,NaN
85,Moncada,2021,Valencia,7,3,172,9,0,113,16,0,6,6,332,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,Las Rozas de Madrid,2020,Madrid,30,0,1063,31,0,453,82,0,64,10,1733,NaN,NaN,NaN,NaN
641,Las Rozas de Madrid,2021,Madrid,21,0,1144,35,0,369,54,0,66,9,1698,NaN,NaN,NaN,NaN
642,Las Rozas de Madrid,2022,Madrid,37,3,1256,54,0,305,84,0,43,14,1796,NaN,NaN,NaN,NaN
643,Las Rozas de Madrid,2023,Madrid,33,2,1321,58,0,389,93,0,34,8,1938,NaN,NaN,NaN,NaN
644,Las Rozas de Madrid,2024,Madrid,48,1,1268,55,0,302,43,0,50,17,1784,NaN,NaN,NaN,NaN

In [40]:
df_unido.head(50)

,Geografía,Año,Provincia,Delitos Sexuales,Homicidios,Hurtos,Lesiones,Resto De Criminalidad Convencional,Robos Con Fuerza,Robos Con Violencia,Secuestro,Sustraccion De Vehiculos,Trafico De Drogas,Total Delitos,Sexo,Municipios,Periodo,Total
0,Alaquàs,2021,Valencia,4,1,205,8,0,100,14,0,10,8,350,Total,Alaquàs,2021.0,29.649
1,Alaquàs,2022,Valencia,5,0,240,14,0,99,21,0,16,7,402,Total,Alaquàs,2022.0,29.537
2,Alaquàs,2023,Valencia,13,0,178,9,0,60,35,1,8,7,311,Total,Alaquàs,2023.0,29.825
3,Alaquàs,2024,Valencia,9,2,188,9,0,77,22,0,12,12,331,Total,Alaquàs,2024.0,30.022
4,Alboraia / Alboraya,2021,Valencia,3,0,391,4,0,86,32,0,16,3,535,NaN,NaN,NaN,NaN
5,Alboraia / Alboraya,2022,Valencia,5,0,529,7,0,121,35,0,30,5,732,NaN,NaN,NaN,NaN
6,Alboraia / Alboraya,2023,Valencia,11,0,530,18,0,145,31,0,25,8,768,NaN,NaN,NaN,NaN
7,Alboraia / Alboraya,2024,Valencia,12,0,628,11,0,207,46,0,19,5,928,NaN,NaN,NaN,NaN
8,Aldaia,2017,Valencia,6,0,1179,8,0,145,34,0,17,5,1394,Total,Aldaia,2017.0,31.320
9,Aldaia,2018,Valencia,5,1,1035,5,0,116,28,0,21,11,1222,Total,Aldaia,2018.0,31.492
10,Aldaia,2019,Valencia,10,0,865,7,0,65,23,0,17,4,991,Total,Aldaia,2019.0,31.864
11,Aldaia,2020,Valencia,7,0,609,14,0,57,24,0,19,2,732,Total,Aldaia,2020.0,32.204
12,Aldaia,2021,Valencia,12,2,848,5,0,83,19,0,15,5,989,Total,Aldaia,2021.0,32.313
13,Aldaia,2022,Valencia,3,0,996,12,0,73,19,0,15,5,1123,Total,Aldaia,2022.0,32.656
14,Aldaia,2023,Valencia,12,1,1092,18,0,59,28,0,15,9,1234,Total,Aldaia,2023.0,33.376
15,Aldaia,2024,Valencia,6,2,942,19,0,108,22,0,29,7,1135,Total,Aldaia,2024.0,34.035
16,Alfafar,2021,Valencia,9,0,512,7,0,61,20,0,12,5,626,Total,Alfafar,2021.0,21.415
17,Alfafar,2022,Valencia,13,0,503,20,0,82,47,0,25,8,698,Total,Alfafar,2022.0,21.480
18,Alfafar,2023,Valencia,13,0,522,10,0,92,39,0,7,3,686,Total,Alfafar,2023.0,21.879
19,Alfafar,2024,Valencia,10,2,488,13,0,84,38,0,13,6,654,Total,Alfafar,2024.0,22.131
20,Algemesí,2021,Valencia,7,0,168,6,0,139,19,0,4,17,360,Total,Algemesí,2021.0,27.305
21,Algemesí,2022,Valencia,7,2,239,8,0,181,18,0,6,5,466,Total,Algemesí,2022.0,27.305
22,Algemesí,2023,Valencia,12,0,251,11,0,126,20,0,10,11,441,Total,Algemesí,2023.0,27.438
23,Algemesí,2024,Valencia,21,3,272,20,0,160,23,0,7,6,512,Total,Algemesí,2024.0,27.968
24,Alzira,2017,Valencia,12,2,476,6,0,296,38,0,21,10,861,Total,Alzira,2017.0,44.255
25,Alzira,2018,Valencia,5,0,538,21,0,367,34,0,22,30,1017,Total,Alzira,2018.0,44.393
26,Alzira,2019,Valencia,14,2,469,23,0,272,36,0,17,21,854,Total,Alzira,2019.0,44.352
27,Alzira,2020,Valencia,20,2,369,19,0,306,31,0,20,28,795,Total,Alzira,2020.0,44.938
28,Alzira,2021,Valencia,28,1,415,25,0,408,38,0,18,22,955,Total,Alzira,2021.0,44.865
29,Alzira,2022,Valencia,11,2,474,26,0,356,39,0,22,9,939,Total,Alzira,2022.0,45.451
30,Alzira,2023,Valencia,34,2,623,30,0,585,43,0,20,24,1361,Total,Alzira,2023.0,46.421
31,Alzira,2024,Valencia,22,3,577,41,0,584,47,0,16,15,1305,Total,Alzira,2024.0,47.335
32,Burjassot,2017,Valencia,2,0,251,6,0,133,32,0,23,5,452,Total,Burjassot,2017.0,37.575
33,Burjassot,2018,Valencia,11,1,276,8,0,97,28,0,29,2,452,Total,Burjassot,2018.0,37.584
34,Burjassot,2019,Valencia,12,3,289,9,0,77,20,0,34,7,451,Total,Burjassot,2019.0,38.024
35,Burjassot,2020,Valencia,7,3,272,8,0,52,17,0,25,7,391,Total,Burjassot,2020.0,38.632
36,Burjassot,2021,Valencia,14,3,367,11,0,127,48,0,18,7,595,Total,Burjassot,2021.0,38.712
37,Burjassot,2022,Valencia,17,3,524,5,0,102,34,0,23,6,714,Total,Burjassot,2022.0,38.880
38,Burjassot,2023,Valencia,18,0,350,3,0,132,28,0,13,12,556,Total,Burjassot,2023.0,39.702
39,Burjassot,2024,Valencia,20,3,368,11,0,140,44,0,16,11,613,Total,Burjassot,2024.0,40.634
40,Bétera,2021,Valencia,19,1,146,3,0,226,12,0,3,6,416,Total,Bétera,2021.0,25.423
41,Bétera,2022,Valencia,11,0,137,12,0,216,22,0,8,2,408,Total,Bétera,2022.0,26.289
42,Bétera,2023,Valencia,11,0,145,16,0,188,20,0,14,3,397,Total,Bétera,2023.0,26.759
43,Bétera,2024,Valencia,17,1,117,20,0,187,14,0,13,2,371,Total,Bétera,2024.0,27.584
44,Carcaixent,2021,Valencia,5,0,197,11,0,59,6,0,3,4,285,Total,Carcaixent,2021.0,20.494
45,Carcaixent,2022,Valencia,10,0,251,12,0,121,14,1,5,6,420,Total,Carcaixent,2022.0,20.498
46,Carcaixent,2023,Valencia,14,0,298,19,0,121,17,0,9,3,481,Total,Carcaixent,2023.0,20.777
47,Carcaixent,2024,Valencia,8,2,259,19,0,112,16,0,6,1,423,Total,Carcaixent,2024.0,21.317
48,Catarroja,2021,Valencia,7,1,197,5,0,172,33,0,13,7,435,Total,Catarroja,2021.0,28.509
49,Catarroja,2022,Valencia,8,0,193,8,0,120,25,0,17,3,374,Total,Catarroja,2022.0,28.679