In [1]:
import pandas as pd
import os

In [2]:
df_crimen = pd.read_csv('/workspaces/sp-ml-20-final-project-g4/data/processed/df_final (5).csv')
df_crimen

,Municipio,Delitos,Año,Periodo,Trimestre,Provincia,Total,Valor trimestral
0,Alaquàs,Delitos Sexuales,2021,Enero-Marzo,1,Valencia,2,2.0
1,Alaquàs,Delitos Sexuales,2021,Enero-Junio,2,Valencia,2,0.0
2,Alaquàs,Delitos Sexuales,2021,Enero-Septiembre,3,Valencia,2,0.0
3,Alaquàs,Delitos Sexuales,2021,Enero-Diciembre,4,Valencia,4,2.0
4,Alaquàs,Delitos Sexuales,2022,Enero-Marzo,1,Valencia,0,0.0
...,...,...,...,...,...,...,...,...
35593,Xàtiva,Trafico De Drogas,2024,Enero-Septiembre,3,Valencia,2,0.0
35594,Xàtiva,Trafico De Drogas,2024,Enero-Diciembre,4,Valencia,4,2.0
35595,Xàtiva,Trafico De Drogas,2025,Enero-Marzo,1,Valencia,2,2.0
35596,Xàtiva,Trafico De Drogas,2025,Enero-Junio,2,Valencia,3,1.0
35597,Xàtiva,Trafico De Drogas,2025,Enero-Septiembre,3,Valencia,3,0.0

In [3]:
df_madrid_p = pd.read_csv('../data/raw/Poblacion/poblacion-madrid.csv', sep=';', encoding='latin1')
df_barcelona_p = pd.read_csv('../data/raw/Poblacion/poblacion-Barcelona.csv', sep=';', encoding='latin1')
df_valencia_p = pd.read_csv('../data/raw/Poblacion/poblacion-valencia.csv', sep=';', encoding='latin1')
df_castellon_p = pd.read_csv('../data/raw/Poblacion/poblacion-castellon.csv', sep=';', encoding='latin1')
df_alicante_p = pd.read_csv('../data/raw/Poblacion/poblacion-alicante.csv', sep=';', encoding='latin1')


df_castellon_p = df_castellon_p.rename(columns={'Municipalities': 'Municipios', 'Sex': 'Sexo', 'Period': 'Periodo'})
df_alicante_p = df_alicante_p.rename(columns={'Municipalities': 'Municipios', 'Sex': 'Sexo', 'Period': 'Periodo'})

In [4]:

df_alicante_p['Municipios'] = df_alicante_p['Municipios'].str.split('/').str[0].str.strip()
df_alicante_p['Municipios'] = df_alicante_p['Municipios'].str.replace(r'^\d+\s+', '', regex=True)
df_alicante_p['Municipios'] = df_alicante_p['Municipios'].replace('Alcoi', 'Alcoy')
df_alicante_p['Municipios'] = df_alicante_p['Municipios'].replace('Campello, el','Campello (el)' )

In [5]:
# Definir los cambios: 'valor_viejo': 'valor_nuevo'
cambios_Alicane = {'Alcoi': 'Alcoy',
                   'Campello, el':'Campello (el)',
                   'Elx':'Elche', 
                   "Alfàs del Pi, l'":"L'Alfàs del Pi"}

df_alicante_p['Municipios'] = df_alicante_p['Municipios'].replace(cambios_Alicane)

In [6]:
# Definir los cambios: 'valor_viejo': 'valor_nuevo'
cambios_Barcelona = {"08101 Hospitalet de Llobregat, L'":"Hospitalet de Llobregat (L')",
                     '08086 Franqueses del Vallès, Les':'Les Franqueses del Vallès',
                     '08118 Masnou, El':'Masnou (El)',
                     '08169 Prat de Llobregat, El':'Prat de Llobregat (El)'}

df_barcelona_p['Municipios'] = df_barcelona_p['Municipios'].replace(cambios_Barcelona)

In [7]:
# Definir los cambios: 'valor_viejo': 'valor_nuevo'
cambios_Madrid = {'28127 Rozas de Madrid, Las':'Las Rozas de Madrid'}

df_madrid_p['Municipios'] = df_madrid_p['Municipios'].replace(cambios_Madrid)

In [8]:
# Definir los cambios: 'valor_viejo': 'valor_nuevo'
cambios_Valencia = {'46171 Montcada/Moncada':'Moncada',
                    '46202 Pobla de Vallbona, la':'Pobla de Vallbona (la)',
                    '46220 Sagunt/Sagunto':'Sagunto'}

df_valencia_p['Municipios'] = df_valencia_p['Municipios'].replace(cambios_Valencia)

In [9]:
# Definir los cambios: 'valor_viejo': 'valor_nuevo'
cambios_Castellon = {"12126 Vall d'Uixó, la":"Vall d'Uixó (la)",
                     '12135 Vila-real':'Vila-Real'}

df_castellon_p['Municipios'] = df_castellon_p['Municipios'].replace(cambios_Castellon)

In [10]:

df_pob = pd.concat([df_madrid_p, df_barcelona_p, df_valencia_p, df_castellon_p,df_alicante_p])
df_pob

       Sexo         Municipios  Periodo  Total
0     Total  28001 Acebeda, La     2025     70
1     Total  28001 Acebeda, La     2024     68
2     Total  28001 Acebeda, La     2023     67
3     Total  28001 Acebeda, La     2022     62
4     Total  28001 Acebeda, La     2021     55
...     ...                ...      ...    ...
1415  Total             Xixona     2020  6,879
1416  Total             Xixona     2019  6,865
1417  Total             Xixona     2018  6,875
1418  Total             Xixona     2017  6,895
1419  Total             Xixona     2016  7,057

[10370 rows x 4 columns]

In [11]:
df_crimen = df_crimen.rename(columns={'Periodo': 'Periodo Trimestral'})
df_pob = df_pob.rename(columns={'Total': 'Poblacion'})

In [12]:
df_pob['Poblacion'] = df_pob['Poblacion'].astype(str).str.replace('.', '', regex=False)

In [13]:

df_pob['Municipio_Clean'] = df_pob['Municipios'].str.replace(r'^\d+\s+', '', regex=True)

In [ ]:
df_pob['Municipio_Clean'] = df_pob['Municipio_Clean'].str.split('/').str[0].str.strip()
df_crimen['Municipio'] = df_crimen['Municipio'].str.split('/').str[0].str.strip()
df_crimen['Municipio'] = df_crimen['Municipio'].str.strip()

In [15]:
df_pob

       Sexo         Municipios  Periodo Poblacion Municipio_Clean
0     Total  28001 Acebeda, La     2025        70     Acebeda, La
1     Total  28001 Acebeda, La     2024        68     Acebeda, La
2     Total  28001 Acebeda, La     2023        67     Acebeda, La
3     Total  28001 Acebeda, La     2022        62     Acebeda, La
4     Total  28001 Acebeda, La     2021        55     Acebeda, La
...     ...                ...      ...       ...             ...
1415  Total             Xixona     2020     6,879          Xixona
1416  Total             Xixona     2019     6,865          Xixona
1417  Total             Xixona     2018     6,875          Xixona
1418  Total             Xixona     2017     6,895          Xixona
1419  Total             Xixona     2016     7,057          Xixona

[10370 rows x 5 columns]

In [16]:
df_pob = df_pob.drop(columns=['Municipios'])
df_pob

       Sexo  Periodo Poblacion Municipio_Clean
0     Total     2025        70     Acebeda, La
1     Total     2024        68     Acebeda, La
2     Total     2023        67     Acebeda, La
3     Total     2022        62     Acebeda, La
4     Total     2021        55     Acebeda, La
...     ...      ...       ...             ...
1415  Total     2020     6,879          Xixona
1416  Total     2019     6,865          Xixona
1417  Total     2018     6,875          Xixona
1418  Total     2017     6,895          Xixona
1419  Total     2016     7,057          Xixona

[10370 rows x 4 columns]

In [17]:
df_crimen

,Municipio,Delitos,Año,Periodo Trimestral,Trimestre,Provincia,Total,Valor trimestral
0,Alaquàs,Delitos Sexuales,2021,Enero-Marzo,1,Valencia,2,2.0
1,Alaquàs,Delitos Sexuales,2021,Enero-Junio,2,Valencia,2,0.0
2,Alaquàs,Delitos Sexuales,2021,Enero-Septiembre,3,Valencia,2,0.0
3,Alaquàs,Delitos Sexuales,2021,Enero-Diciembre,4,Valencia,4,2.0
4,Alaquàs,Delitos Sexuales,2022,Enero-Marzo,1,Valencia,0,0.0
...,...,...,...,...,...,...,...,...
35593,Xàtiva,Trafico De Drogas,2024,Enero-Septiembre,3,Valencia,2,0.0
35594,Xàtiva,Trafico De Drogas,2024,Enero-Diciembre,4,Valencia,4,2.0
35595,Xàtiva,Trafico De Drogas,2025,Enero-Marzo,1,Valencia,2,2.0
35596,Xàtiva,Trafico De Drogas,2025,Enero-Junio,2,Valencia,3,1.0
35597,Xàtiva,Trafico De Drogas,2025,Enero-Septiembre,3,Valencia,3,0.0

In [ ]:
# Unimos por Municipio_Clean y por el Año (que en df_pob se llama 'Periodo')
df_merged = df_crimen.merge(df_pob[['Municipio_Clean', 'Periodo', 'Poblacion']], 
                            left_on=['Municipio', 'Año'], 
                            right_on=['Municipio_Clean', 'Periodo'], 
                            how='left')
df_merged

,Municipio,Delitos,Año,Periodo Trimestral,Trimestre,Provincia,Total,Valor trimestral,Municipio_Clean,Periodo,Poblacion
0,Alaquàs,Delitos Sexuales,2021,Enero-Marzo,1,Valencia,2,2.0,Alaquàs,2021,29649
1,Alaquàs,Delitos Sexuales,2021,Enero-Junio,2,Valencia,2,0.0,Alaquàs,2021,29649
2,Alaquàs,Delitos Sexuales,2021,Enero-Septiembre,3,Valencia,2,0.0,Alaquàs,2021,29649
3,Alaquàs,Delitos Sexuales,2021,Enero-Diciembre,4,Valencia,4,2.0,Alaquàs,2021,29649
4,Alaquàs,Delitos Sexuales,2022,Enero-Marzo,1,Valencia,0,0.0,Alaquàs,2022,29537
...,...,...,...,...,...,...,...,...,...,...,...
36239,Xàtiva,Trafico De Drogas,2024,Enero-Septiembre,3,Valencia,2,0.0,Xàtiva,2024,30378
36240,Xàtiva,Trafico De Drogas,2024,Enero-Diciembre,4,Valencia,4,2.0,Xàtiva,2024,30378
36241,Xàtiva,Trafico De Drogas,2025,Enero-Marzo,1,Valencia,2,2.0,Xàtiva,2025,31008
36242,Xàtiva,Trafico De Drogas,2025,Enero-Junio,2,Valencia,3,1.0,Xàtiva,2025,31008
36243,Xàtiva,Trafico De Drogas,2025,Enero-Septiembre,3,Valencia,3,0.0,Xàtiva,2025,31008

In [19]:
df_merged = df_merged.drop(columns=['Municipio_Clean', 'Periodo'])
df_merged

,Municipio,Delitos,Año,Periodo Trimestral,Trimestre,Provincia,Total,Valor trimestral,Poblacion
0,Alaquàs,Delitos Sexuales,2021,Enero-Marzo,1,Valencia,2,2.0,29649
1,Alaquàs,Delitos Sexuales,2021,Enero-Junio,2,Valencia,2,0.0,29649
2,Alaquàs,Delitos Sexuales,2021,Enero-Septiembre,3,Valencia,2,0.0,29649
3,Alaquàs,Delitos Sexuales,2021,Enero-Diciembre,4,Valencia,4,2.0,29649
4,Alaquàs,Delitos Sexuales,2022,Enero-Marzo,1,Valencia,0,0.0,29537
...,...,...,...,...,...,...,...,...,...
36239,Xàtiva,Trafico De Drogas,2024,Enero-Septiembre,3,Valencia,2,0.0,30378
36240,Xàtiva,Trafico De Drogas,2024,Enero-Diciembre,4,Valencia,4,2.0,30378
36241,Xàtiva,Trafico De Drogas,2025,Enero-Marzo,1,Valencia,2,2.0,31008
36242,Xàtiva,Trafico De Drogas,2025,Enero-Junio,2,Valencia,3,1.0,31008
36243,Xàtiva,Trafico De Drogas,2025,Enero-Septiembre,3,Valencia,3,0.0,31008

In [20]:
df_merged.isna().sum()

Municipio             0
Delitos               0
Año                   0
Periodo Trimestral    0
Trimestre             0
Provincia             0
Total                 0
Valor trimestral      0
Poblacion             0
dtype: int64

In [21]:
df_merged.to_csv("../data/processed/df_final_poblacion.csv", index=False)